---
root: true
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: false
extends: standard
plugins:
- html
rules:
  # Allow paren-less arrow functions
  arrow-parens: 0
  # Allow async-await
  generator-star-spacing: 0
