options:
  merge-default-rules: true
files:
  include:
  - '**/**.sass'
# - '**/**.vue'
rules:
  indentation:
  - 2
  -
    size: 2
  class-name-format:
  - 2
  -
    allow-leading-underscore: false
    convention: camelcase
