os:
- linux
- osx
language: node_js
node_js: node
cache:
  directories:
  - node_modules
sudo: false
matrix:
  fast_finish: true
before_install:
- npm update && npm prune
install:
- travis_retry npm i
before_script:
- npm test
script:
- npm run build
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash build/deploy.sh
- bash <(curl -s https://codecov.io/bash)
